services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:Postgres123!!@db:5432/transactions_management
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared_network
  db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123!!
      POSTGRES_DB: transactions_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network

volumes:
  postgres_data:

networks:
  shared_network:
    external: true
