version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:Postgres123!!@db:5433/transactions_management
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123!!
      POSTGRES_DB: transactions_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
